### ISSUE TITLE
Question and improvement proposal

### ISSUE THREAD

**Issue by mquinzin** [mini-bomba/create-github-release#3]
Hi (again), I'm not sure to have understood correctly the way your script runs.
If I set the tag and release fields, I suppose the tag and release will be created by I have the message:
 👀 Checking current state of the release
  File "/src/main.py", line 109, in <module>
    release = repo.get_release(tag_name)
  File "/usr/local/lib/python3.9/site-packages/github/Repository.py", line 3053, in get_release
    headers, data = self._requester.requestJsonAndCheck(
  File "/usr/local/lib/python3.9/site-packages/github/Requester.py", line 353, in requestJsonAndCheck
    return self.__check(
  File "/usr/local/lib/python3.9/site-packages/github/Requester.py", line 378, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.UnknownObjectException: 404 {"message": "Not Found", "documentation_url": "https://docs.github.com/rest/reference/repos#get-a-release-by-tag-name"}

If I create the tag and release before, the script says:
  fatal: tag 'dev-20220621' already exists

So what is the correct way to use it ?
Would it be possible to consider that tag/release could already exist (we just want to upgrade fields and assets).

Thanks for your help.

**Comment by mini-bomba** [comment]
It was supposed to create the tag if it doesn't exist, move it if it does.
Not sure what's up with it not working...
It seems you're adding the current date to the tag name, is that correct?
I'll do some testing to find out why this is happening and create a fix.

**Comment by mquinzin** [comment]
Yes I use the date in the tag.
Your code does:
# Create/move tag
print("::group::🏷️ Creating/Moving the tag...")
gitproc = subprocess.Popen(["git", "tag", tag_name, target_commit], stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
out, _ = gitproc.communicate()
print("::stop-commands::git-output")
print(out.decode())
if gitproc.returncode != 0:
    print("::git-output::")
    print("::endgroup::")
    print(f"::error::❌ Command 'git tag {tag_name} {target_commit}' returned with non-zero exit code!")
    exit(gitproc.returncode)

So if I understand correctly, you run the git tag command every time.
Yesterday before executing your script I was doing the action snow-actions/sparse-checkout@v1.1.0 that checkout the git repository but not in an entire way. In this environment the tag was not known.
But now I want to use the normal actions/checkout@v2 that checkout the whole git repository and all metadata. In this case the tag is already existing, and so your script fails then.

Hope I'm clear enough.

**Comment by mini-bomba** [comment]
I've just released v1.1.1, which fixes the mentioned issues.
This was mostly some oversights on my part, I didn't know that actions/checkout@v2 ignored tags by default, and didn't expect PyGithub to throw an error when release does not exist.
I've added code catching the error from PyGithub and I've added a force flag to the `git tag` command.
